name: Cloud189 Checkin

on:
  schedule:
    - cron: '10 2 * * *'  # 每天 UTC 2:10 执行（北京时间早上 10:10）
  workflow_dispatch:  # 支持手动触发

jobs:
  CheckIn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests rsa

      - name: Run script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          TG: ${{ secrets.TG }}
          UA: ${{ secrets.UA }}
          MODEL: ${{ secrets.MODEL }}
        run: |
          python checkin.py
