name: Cloud189 Checkin

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 执行（北京时间早上 9:00）
  workflow_dispatch:  # 支持手动触发

jobs:
  CheckIn:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 建立Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install requests rsa

      - name: 运行脚本
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          TG: ${{ secrets.TG }}
          UA: ${{ secrets.UA }}
          MODEL: ${{ secrets.MODEL }}
        run: |
          python checkin.py
